# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ubuntu/CANOpenRobotController

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ubuntu/CANOpenRobotController

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/CANOpenRobotController/CMakeFiles /home/ubuntu/CANOpenRobotController/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/CANOpenRobotController/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named M1DemoMachine_APP

# Build rule for target.
M1DemoMachine_APP: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 M1DemoMachine_APP
.PHONY : M1DemoMachine_APP

# fast build rule for target.
M1DemoMachine_APP/fast:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/build
.PHONY : M1DemoMachine_APP/fast

src/apps/M1DemoMachine/M1DemoMachine.o: src/apps/M1DemoMachine/M1DemoMachine.cpp.o

.PHONY : src/apps/M1DemoMachine/M1DemoMachine.o

# target to build an object file
src/apps/M1DemoMachine/M1DemoMachine.cpp.o:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/apps/M1DemoMachine/M1DemoMachine.cpp.o
.PHONY : src/apps/M1DemoMachine/M1DemoMachine.cpp.o

src/apps/M1DemoMachine/M1DemoMachine.i: src/apps/M1DemoMachine/M1DemoMachine.cpp.i

.PHONY : src/apps/M1DemoMachine/M1DemoMachine.i

# target to preprocess a source file
src/apps/M1DemoMachine/M1DemoMachine.cpp.i:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/apps/M1DemoMachine/M1DemoMachine.cpp.i
.PHONY : src/apps/M1DemoMachine/M1DemoMachine.cpp.i

src/apps/M1DemoMachine/M1DemoMachine.s: src/apps/M1DemoMachine/M1DemoMachine.cpp.s

.PHONY : src/apps/M1DemoMachine/M1DemoMachine.s

# target to generate assembly for a file
src/apps/M1DemoMachine/M1DemoMachine.cpp.s:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/apps/M1DemoMachine/M1DemoMachine.cpp.s
.PHONY : src/apps/M1DemoMachine/M1DemoMachine.cpp.s

src/apps/M1DemoMachine/M1DemoStates.o: src/apps/M1DemoMachine/M1DemoStates.cpp.o

.PHONY : src/apps/M1DemoMachine/M1DemoStates.o

# target to build an object file
src/apps/M1DemoMachine/M1DemoStates.cpp.o:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/apps/M1DemoMachine/M1DemoStates.cpp.o
.PHONY : src/apps/M1DemoMachine/M1DemoStates.cpp.o

src/apps/M1DemoMachine/M1DemoStates.i: src/apps/M1DemoMachine/M1DemoStates.cpp.i

.PHONY : src/apps/M1DemoMachine/M1DemoStates.i

# target to preprocess a source file
src/apps/M1DemoMachine/M1DemoStates.cpp.i:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/apps/M1DemoMachine/M1DemoStates.cpp.i
.PHONY : src/apps/M1DemoMachine/M1DemoStates.cpp.i

src/apps/M1DemoMachine/M1DemoStates.s: src/apps/M1DemoMachine/M1DemoStates.cpp.s

.PHONY : src/apps/M1DemoMachine/M1DemoStates.s

# target to generate assembly for a file
src/apps/M1DemoMachine/M1DemoStates.cpp.s:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/apps/M1DemoMachine/M1DemoStates.cpp.s
.PHONY : src/apps/M1DemoMachine/M1DemoStates.cpp.s

src/core/CANopen/CANcomms/CO_comm_helpers.o: src/core/CANopen/CANcomms/CO_comm_helpers.c.o

.PHONY : src/core/CANopen/CANcomms/CO_comm_helpers.o

# target to build an object file
src/core/CANopen/CANcomms/CO_comm_helpers.c.o:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANcomms/CO_comm_helpers.c.o
.PHONY : src/core/CANopen/CANcomms/CO_comm_helpers.c.o

src/core/CANopen/CANcomms/CO_comm_helpers.i: src/core/CANopen/CANcomms/CO_comm_helpers.c.i

.PHONY : src/core/CANopen/CANcomms/CO_comm_helpers.i

# target to preprocess a source file
src/core/CANopen/CANcomms/CO_comm_helpers.c.i:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANcomms/CO_comm_helpers.c.i
.PHONY : src/core/CANopen/CANcomms/CO_comm_helpers.c.i

src/core/CANopen/CANcomms/CO_comm_helpers.s: src/core/CANopen/CANcomms/CO_comm_helpers.c.s

.PHONY : src/core/CANopen/CANcomms/CO_comm_helpers.s

# target to generate assembly for a file
src/core/CANopen/CANcomms/CO_comm_helpers.c.s:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANcomms/CO_comm_helpers.c.s
.PHONY : src/core/CANopen/CANcomms/CO_comm_helpers.c.s

src/core/CANopen/CANcomms/CO_command.o: src/core/CANopen/CANcomms/CO_command.c.o

.PHONY : src/core/CANopen/CANcomms/CO_command.o

# target to build an object file
src/core/CANopen/CANcomms/CO_command.c.o:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANcomms/CO_command.c.o
.PHONY : src/core/CANopen/CANcomms/CO_command.c.o

src/core/CANopen/CANcomms/CO_command.i: src/core/CANopen/CANcomms/CO_command.c.i

.PHONY : src/core/CANopen/CANcomms/CO_command.i

# target to preprocess a source file
src/core/CANopen/CANcomms/CO_command.c.i:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANcomms/CO_command.c.i
.PHONY : src/core/CANopen/CANcomms/CO_command.c.i

src/core/CANopen/CANcomms/CO_command.s: src/core/CANopen/CANcomms/CO_command.c.s

.PHONY : src/core/CANopen/CANcomms/CO_command.s

# target to generate assembly for a file
src/core/CANopen/CANcomms/CO_command.c.s:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANcomms/CO_command.c.s
.PHONY : src/core/CANopen/CANcomms/CO_command.c.s

src/core/CANopen/CANcomms/CO_master.o: src/core/CANopen/CANcomms/CO_master.c.o

.PHONY : src/core/CANopen/CANcomms/CO_master.o

# target to build an object file
src/core/CANopen/CANcomms/CO_master.c.o:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANcomms/CO_master.c.o
.PHONY : src/core/CANopen/CANcomms/CO_master.c.o

src/core/CANopen/CANcomms/CO_master.i: src/core/CANopen/CANcomms/CO_master.c.i

.PHONY : src/core/CANopen/CANcomms/CO_master.i

# target to preprocess a source file
src/core/CANopen/CANcomms/CO_master.c.i:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANcomms/CO_master.c.i
.PHONY : src/core/CANopen/CANcomms/CO_master.c.i

src/core/CANopen/CANcomms/CO_master.s: src/core/CANopen/CANcomms/CO_master.c.s

.PHONY : src/core/CANopen/CANcomms/CO_master.s

# target to generate assembly for a file
src/core/CANopen/CANcomms/CO_master.c.s:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANcomms/CO_master.c.s
.PHONY : src/core/CANopen/CANcomms/CO_master.c.s

src/core/CANopen/CANcomms/CO_time.o: src/core/CANopen/CANcomms/CO_time.c.o

.PHONY : src/core/CANopen/CANcomms/CO_time.o

# target to build an object file
src/core/CANopen/CANcomms/CO_time.c.o:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANcomms/CO_time.c.o
.PHONY : src/core/CANopen/CANcomms/CO_time.c.o

src/core/CANopen/CANcomms/CO_time.i: src/core/CANopen/CANcomms/CO_time.c.i

.PHONY : src/core/CANopen/CANcomms/CO_time.i

# target to preprocess a source file
src/core/CANopen/CANcomms/CO_time.c.i:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANcomms/CO_time.c.i
.PHONY : src/core/CANopen/CANcomms/CO_time.c.i

src/core/CANopen/CANcomms/CO_time.s: src/core/CANopen/CANcomms/CO_time.c.s

.PHONY : src/core/CANopen/CANcomms/CO_time.s

# target to generate assembly for a file
src/core/CANopen/CANcomms/CO_time.c.s:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANcomms/CO_time.c.s
.PHONY : src/core/CANopen/CANcomms/CO_time.c.s

src/core/CANopen/CANopenNode/CANopen.o: src/core/CANopen/CANopenNode/CANopen.c.o

.PHONY : src/core/CANopen/CANopenNode/CANopen.o

# target to build an object file
src/core/CANopen/CANopenNode/CANopen.c.o:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANopenNode/CANopen.c.o
.PHONY : src/core/CANopen/CANopenNode/CANopen.c.o

src/core/CANopen/CANopenNode/CANopen.i: src/core/CANopen/CANopenNode/CANopen.c.i

.PHONY : src/core/CANopen/CANopenNode/CANopen.i

# target to preprocess a source file
src/core/CANopen/CANopenNode/CANopen.c.i:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANopenNode/CANopen.c.i
.PHONY : src/core/CANopen/CANopenNode/CANopen.c.i

src/core/CANopen/CANopenNode/CANopen.s: src/core/CANopen/CANopenNode/CANopen.c.s

.PHONY : src/core/CANopen/CANopenNode/CANopen.s

# target to generate assembly for a file
src/core/CANopen/CANopenNode/CANopen.c.s:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANopenNode/CANopen.c.s
.PHONY : src/core/CANopen/CANopenNode/CANopen.c.s

src/core/CANopen/CANopenNode/stack/CO_Emergency.o: src/core/CANopen/CANopenNode/stack/CO_Emergency.c.o

.PHONY : src/core/CANopen/CANopenNode/stack/CO_Emergency.o

# target to build an object file
src/core/CANopen/CANopenNode/stack/CO_Emergency.c.o:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANopenNode/stack/CO_Emergency.c.o
.PHONY : src/core/CANopen/CANopenNode/stack/CO_Emergency.c.o

src/core/CANopen/CANopenNode/stack/CO_Emergency.i: src/core/CANopen/CANopenNode/stack/CO_Emergency.c.i

.PHONY : src/core/CANopen/CANopenNode/stack/CO_Emergency.i

# target to preprocess a source file
src/core/CANopen/CANopenNode/stack/CO_Emergency.c.i:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANopenNode/stack/CO_Emergency.c.i
.PHONY : src/core/CANopen/CANopenNode/stack/CO_Emergency.c.i

src/core/CANopen/CANopenNode/stack/CO_Emergency.s: src/core/CANopen/CANopenNode/stack/CO_Emergency.c.s

.PHONY : src/core/CANopen/CANopenNode/stack/CO_Emergency.s

# target to generate assembly for a file
src/core/CANopen/CANopenNode/stack/CO_Emergency.c.s:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANopenNode/stack/CO_Emergency.c.s
.PHONY : src/core/CANopen/CANopenNode/stack/CO_Emergency.c.s

src/core/CANopen/CANopenNode/stack/CO_HBconsumer.o: src/core/CANopen/CANopenNode/stack/CO_HBconsumer.c.o

.PHONY : src/core/CANopen/CANopenNode/stack/CO_HBconsumer.o

# target to build an object file
src/core/CANopen/CANopenNode/stack/CO_HBconsumer.c.o:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANopenNode/stack/CO_HBconsumer.c.o
.PHONY : src/core/CANopen/CANopenNode/stack/CO_HBconsumer.c.o

src/core/CANopen/CANopenNode/stack/CO_HBconsumer.i: src/core/CANopen/CANopenNode/stack/CO_HBconsumer.c.i

.PHONY : src/core/CANopen/CANopenNode/stack/CO_HBconsumer.i

# target to preprocess a source file
src/core/CANopen/CANopenNode/stack/CO_HBconsumer.c.i:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANopenNode/stack/CO_HBconsumer.c.i
.PHONY : src/core/CANopen/CANopenNode/stack/CO_HBconsumer.c.i

src/core/CANopen/CANopenNode/stack/CO_HBconsumer.s: src/core/CANopen/CANopenNode/stack/CO_HBconsumer.c.s

.PHONY : src/core/CANopen/CANopenNode/stack/CO_HBconsumer.s

# target to generate assembly for a file
src/core/CANopen/CANopenNode/stack/CO_HBconsumer.c.s:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANopenNode/stack/CO_HBconsumer.c.s
.PHONY : src/core/CANopen/CANopenNode/stack/CO_HBconsumer.c.s

src/core/CANopen/CANopenNode/stack/CO_NMT_Heartbeat.o: src/core/CANopen/CANopenNode/stack/CO_NMT_Heartbeat.c.o

.PHONY : src/core/CANopen/CANopenNode/stack/CO_NMT_Heartbeat.o

# target to build an object file
src/core/CANopen/CANopenNode/stack/CO_NMT_Heartbeat.c.o:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANopenNode/stack/CO_NMT_Heartbeat.c.o
.PHONY : src/core/CANopen/CANopenNode/stack/CO_NMT_Heartbeat.c.o

src/core/CANopen/CANopenNode/stack/CO_NMT_Heartbeat.i: src/core/CANopen/CANopenNode/stack/CO_NMT_Heartbeat.c.i

.PHONY : src/core/CANopen/CANopenNode/stack/CO_NMT_Heartbeat.i

# target to preprocess a source file
src/core/CANopen/CANopenNode/stack/CO_NMT_Heartbeat.c.i:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANopenNode/stack/CO_NMT_Heartbeat.c.i
.PHONY : src/core/CANopen/CANopenNode/stack/CO_NMT_Heartbeat.c.i

src/core/CANopen/CANopenNode/stack/CO_NMT_Heartbeat.s: src/core/CANopen/CANopenNode/stack/CO_NMT_Heartbeat.c.s

.PHONY : src/core/CANopen/CANopenNode/stack/CO_NMT_Heartbeat.s

# target to generate assembly for a file
src/core/CANopen/CANopenNode/stack/CO_NMT_Heartbeat.c.s:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANopenNode/stack/CO_NMT_Heartbeat.c.s
.PHONY : src/core/CANopen/CANopenNode/stack/CO_NMT_Heartbeat.c.s

src/core/CANopen/CANopenNode/stack/CO_PDO.o: src/core/CANopen/CANopenNode/stack/CO_PDO.c.o

.PHONY : src/core/CANopen/CANopenNode/stack/CO_PDO.o

# target to build an object file
src/core/CANopen/CANopenNode/stack/CO_PDO.c.o:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANopenNode/stack/CO_PDO.c.o
.PHONY : src/core/CANopen/CANopenNode/stack/CO_PDO.c.o

src/core/CANopen/CANopenNode/stack/CO_PDO.i: src/core/CANopen/CANopenNode/stack/CO_PDO.c.i

.PHONY : src/core/CANopen/CANopenNode/stack/CO_PDO.i

# target to preprocess a source file
src/core/CANopen/CANopenNode/stack/CO_PDO.c.i:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANopenNode/stack/CO_PDO.c.i
.PHONY : src/core/CANopen/CANopenNode/stack/CO_PDO.c.i

src/core/CANopen/CANopenNode/stack/CO_PDO.s: src/core/CANopen/CANopenNode/stack/CO_PDO.c.s

.PHONY : src/core/CANopen/CANopenNode/stack/CO_PDO.s

# target to generate assembly for a file
src/core/CANopen/CANopenNode/stack/CO_PDO.c.s:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANopenNode/stack/CO_PDO.c.s
.PHONY : src/core/CANopen/CANopenNode/stack/CO_PDO.c.s

src/core/CANopen/CANopenNode/stack/CO_SDO.o: src/core/CANopen/CANopenNode/stack/CO_SDO.c.o

.PHONY : src/core/CANopen/CANopenNode/stack/CO_SDO.o

# target to build an object file
src/core/CANopen/CANopenNode/stack/CO_SDO.c.o:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANopenNode/stack/CO_SDO.c.o
.PHONY : src/core/CANopen/CANopenNode/stack/CO_SDO.c.o

src/core/CANopen/CANopenNode/stack/CO_SDO.i: src/core/CANopen/CANopenNode/stack/CO_SDO.c.i

.PHONY : src/core/CANopen/CANopenNode/stack/CO_SDO.i

# target to preprocess a source file
src/core/CANopen/CANopenNode/stack/CO_SDO.c.i:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANopenNode/stack/CO_SDO.c.i
.PHONY : src/core/CANopen/CANopenNode/stack/CO_SDO.c.i

src/core/CANopen/CANopenNode/stack/CO_SDO.s: src/core/CANopen/CANopenNode/stack/CO_SDO.c.s

.PHONY : src/core/CANopen/CANopenNode/stack/CO_SDO.s

# target to generate assembly for a file
src/core/CANopen/CANopenNode/stack/CO_SDO.c.s:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANopenNode/stack/CO_SDO.c.s
.PHONY : src/core/CANopen/CANopenNode/stack/CO_SDO.c.s

src/core/CANopen/CANopenNode/stack/CO_SDOmaster.o: src/core/CANopen/CANopenNode/stack/CO_SDOmaster.c.o

.PHONY : src/core/CANopen/CANopenNode/stack/CO_SDOmaster.o

# target to build an object file
src/core/CANopen/CANopenNode/stack/CO_SDOmaster.c.o:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANopenNode/stack/CO_SDOmaster.c.o
.PHONY : src/core/CANopen/CANopenNode/stack/CO_SDOmaster.c.o

src/core/CANopen/CANopenNode/stack/CO_SDOmaster.i: src/core/CANopen/CANopenNode/stack/CO_SDOmaster.c.i

.PHONY : src/core/CANopen/CANopenNode/stack/CO_SDOmaster.i

# target to preprocess a source file
src/core/CANopen/CANopenNode/stack/CO_SDOmaster.c.i:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANopenNode/stack/CO_SDOmaster.c.i
.PHONY : src/core/CANopen/CANopenNode/stack/CO_SDOmaster.c.i

src/core/CANopen/CANopenNode/stack/CO_SDOmaster.s: src/core/CANopen/CANopenNode/stack/CO_SDOmaster.c.s

.PHONY : src/core/CANopen/CANopenNode/stack/CO_SDOmaster.s

# target to generate assembly for a file
src/core/CANopen/CANopenNode/stack/CO_SDOmaster.c.s:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANopenNode/stack/CO_SDOmaster.c.s
.PHONY : src/core/CANopen/CANopenNode/stack/CO_SDOmaster.c.s

src/core/CANopen/CANopenNode/stack/CO_SYNC.o: src/core/CANopen/CANopenNode/stack/CO_SYNC.c.o

.PHONY : src/core/CANopen/CANopenNode/stack/CO_SYNC.o

# target to build an object file
src/core/CANopen/CANopenNode/stack/CO_SYNC.c.o:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANopenNode/stack/CO_SYNC.c.o
.PHONY : src/core/CANopen/CANopenNode/stack/CO_SYNC.c.o

src/core/CANopen/CANopenNode/stack/CO_SYNC.i: src/core/CANopen/CANopenNode/stack/CO_SYNC.c.i

.PHONY : src/core/CANopen/CANopenNode/stack/CO_SYNC.i

# target to preprocess a source file
src/core/CANopen/CANopenNode/stack/CO_SYNC.c.i:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANopenNode/stack/CO_SYNC.c.i
.PHONY : src/core/CANopen/CANopenNode/stack/CO_SYNC.c.i

src/core/CANopen/CANopenNode/stack/CO_SYNC.s: src/core/CANopen/CANopenNode/stack/CO_SYNC.c.s

.PHONY : src/core/CANopen/CANopenNode/stack/CO_SYNC.s

# target to generate assembly for a file
src/core/CANopen/CANopenNode/stack/CO_SYNC.c.s:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANopenNode/stack/CO_SYNC.c.s
.PHONY : src/core/CANopen/CANopenNode/stack/CO_SYNC.c.s

src/core/CANopen/CANopenNode/stack/CO_trace.o: src/core/CANopen/CANopenNode/stack/CO_trace.c.o

.PHONY : src/core/CANopen/CANopenNode/stack/CO_trace.o

# target to build an object file
src/core/CANopen/CANopenNode/stack/CO_trace.c.o:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANopenNode/stack/CO_trace.c.o
.PHONY : src/core/CANopen/CANopenNode/stack/CO_trace.c.o

src/core/CANopen/CANopenNode/stack/CO_trace.i: src/core/CANopen/CANopenNode/stack/CO_trace.c.i

.PHONY : src/core/CANopen/CANopenNode/stack/CO_trace.i

# target to preprocess a source file
src/core/CANopen/CANopenNode/stack/CO_trace.c.i:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANopenNode/stack/CO_trace.c.i
.PHONY : src/core/CANopen/CANopenNode/stack/CO_trace.c.i

src/core/CANopen/CANopenNode/stack/CO_trace.s: src/core/CANopen/CANopenNode/stack/CO_trace.c.s

.PHONY : src/core/CANopen/CANopenNode/stack/CO_trace.s

# target to generate assembly for a file
src/core/CANopen/CANopenNode/stack/CO_trace.c.s:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANopenNode/stack/CO_trace.c.s
.PHONY : src/core/CANopen/CANopenNode/stack/CO_trace.c.s

src/core/CANopen/CANopenNode/stack/crc16-ccitt.o: src/core/CANopen/CANopenNode/stack/crc16-ccitt.c.o

.PHONY : src/core/CANopen/CANopenNode/stack/crc16-ccitt.o

# target to build an object file
src/core/CANopen/CANopenNode/stack/crc16-ccitt.c.o:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANopenNode/stack/crc16-ccitt.c.o
.PHONY : src/core/CANopen/CANopenNode/stack/crc16-ccitt.c.o

src/core/CANopen/CANopenNode/stack/crc16-ccitt.i: src/core/CANopen/CANopenNode/stack/crc16-ccitt.c.i

.PHONY : src/core/CANopen/CANopenNode/stack/crc16-ccitt.i

# target to preprocess a source file
src/core/CANopen/CANopenNode/stack/crc16-ccitt.c.i:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANopenNode/stack/crc16-ccitt.c.i
.PHONY : src/core/CANopen/CANopenNode/stack/crc16-ccitt.c.i

src/core/CANopen/CANopenNode/stack/crc16-ccitt.s: src/core/CANopen/CANopenNode/stack/crc16-ccitt.c.s

.PHONY : src/core/CANopen/CANopenNode/stack/crc16-ccitt.s

# target to generate assembly for a file
src/core/CANopen/CANopenNode/stack/crc16-ccitt.c.s:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANopenNode/stack/crc16-ccitt.c.s
.PHONY : src/core/CANopen/CANopenNode/stack/crc16-ccitt.c.s

src/core/CANopen/CANopenNode/stack/socketCAN/CO_Linux_tasks.o: src/core/CANopen/CANopenNode/stack/socketCAN/CO_Linux_tasks.c.o

.PHONY : src/core/CANopen/CANopenNode/stack/socketCAN/CO_Linux_tasks.o

# target to build an object file
src/core/CANopen/CANopenNode/stack/socketCAN/CO_Linux_tasks.c.o:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANopenNode/stack/socketCAN/CO_Linux_tasks.c.o
.PHONY : src/core/CANopen/CANopenNode/stack/socketCAN/CO_Linux_tasks.c.o

src/core/CANopen/CANopenNode/stack/socketCAN/CO_Linux_tasks.i: src/core/CANopen/CANopenNode/stack/socketCAN/CO_Linux_tasks.c.i

.PHONY : src/core/CANopen/CANopenNode/stack/socketCAN/CO_Linux_tasks.i

# target to preprocess a source file
src/core/CANopen/CANopenNode/stack/socketCAN/CO_Linux_tasks.c.i:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANopenNode/stack/socketCAN/CO_Linux_tasks.c.i
.PHONY : src/core/CANopen/CANopenNode/stack/socketCAN/CO_Linux_tasks.c.i

src/core/CANopen/CANopenNode/stack/socketCAN/CO_Linux_tasks.s: src/core/CANopen/CANopenNode/stack/socketCAN/CO_Linux_tasks.c.s

.PHONY : src/core/CANopen/CANopenNode/stack/socketCAN/CO_Linux_tasks.s

# target to generate assembly for a file
src/core/CANopen/CANopenNode/stack/socketCAN/CO_Linux_tasks.c.s:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANopenNode/stack/socketCAN/CO_Linux_tasks.c.s
.PHONY : src/core/CANopen/CANopenNode/stack/socketCAN/CO_Linux_tasks.c.s

src/core/CANopen/CANopenNode/stack/socketCAN/CO_OD_storage.o: src/core/CANopen/CANopenNode/stack/socketCAN/CO_OD_storage.c.o

.PHONY : src/core/CANopen/CANopenNode/stack/socketCAN/CO_OD_storage.o

# target to build an object file
src/core/CANopen/CANopenNode/stack/socketCAN/CO_OD_storage.c.o:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANopenNode/stack/socketCAN/CO_OD_storage.c.o
.PHONY : src/core/CANopen/CANopenNode/stack/socketCAN/CO_OD_storage.c.o

src/core/CANopen/CANopenNode/stack/socketCAN/CO_OD_storage.i: src/core/CANopen/CANopenNode/stack/socketCAN/CO_OD_storage.c.i

.PHONY : src/core/CANopen/CANopenNode/stack/socketCAN/CO_OD_storage.i

# target to preprocess a source file
src/core/CANopen/CANopenNode/stack/socketCAN/CO_OD_storage.c.i:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANopenNode/stack/socketCAN/CO_OD_storage.c.i
.PHONY : src/core/CANopen/CANopenNode/stack/socketCAN/CO_OD_storage.c.i

src/core/CANopen/CANopenNode/stack/socketCAN/CO_OD_storage.s: src/core/CANopen/CANopenNode/stack/socketCAN/CO_OD_storage.c.s

.PHONY : src/core/CANopen/CANopenNode/stack/socketCAN/CO_OD_storage.s

# target to generate assembly for a file
src/core/CANopen/CANopenNode/stack/socketCAN/CO_OD_storage.c.s:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANopenNode/stack/socketCAN/CO_OD_storage.c.s
.PHONY : src/core/CANopen/CANopenNode/stack/socketCAN/CO_OD_storage.c.s

src/core/CANopen/CANopenNode/stack/socketCAN/CO_driver.o: src/core/CANopen/CANopenNode/stack/socketCAN/CO_driver.c.o

.PHONY : src/core/CANopen/CANopenNode/stack/socketCAN/CO_driver.o

# target to build an object file
src/core/CANopen/CANopenNode/stack/socketCAN/CO_driver.c.o:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANopenNode/stack/socketCAN/CO_driver.c.o
.PHONY : src/core/CANopen/CANopenNode/stack/socketCAN/CO_driver.c.o

src/core/CANopen/CANopenNode/stack/socketCAN/CO_driver.i: src/core/CANopen/CANopenNode/stack/socketCAN/CO_driver.c.i

.PHONY : src/core/CANopen/CANopenNode/stack/socketCAN/CO_driver.i

# target to preprocess a source file
src/core/CANopen/CANopenNode/stack/socketCAN/CO_driver.c.i:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANopenNode/stack/socketCAN/CO_driver.c.i
.PHONY : src/core/CANopen/CANopenNode/stack/socketCAN/CO_driver.c.i

src/core/CANopen/CANopenNode/stack/socketCAN/CO_driver.s: src/core/CANopen/CANopenNode/stack/socketCAN/CO_driver.c.s

.PHONY : src/core/CANopen/CANopenNode/stack/socketCAN/CO_driver.s

# target to generate assembly for a file
src/core/CANopen/CANopenNode/stack/socketCAN/CO_driver.c.s:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/CANopenNode/stack/socketCAN/CO_driver.c.s
.PHONY : src/core/CANopen/CANopenNode/stack/socketCAN/CO_driver.c.s

src/core/CANopen/objDict/CO_OD.o: src/core/CANopen/objDict/CO_OD.c.o

.PHONY : src/core/CANopen/objDict/CO_OD.o

# target to build an object file
src/core/CANopen/objDict/CO_OD.c.o:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/objDict/CO_OD.c.o
.PHONY : src/core/CANopen/objDict/CO_OD.c.o

src/core/CANopen/objDict/CO_OD.i: src/core/CANopen/objDict/CO_OD.c.i

.PHONY : src/core/CANopen/objDict/CO_OD.i

# target to preprocess a source file
src/core/CANopen/objDict/CO_OD.c.i:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/objDict/CO_OD.c.i
.PHONY : src/core/CANopen/objDict/CO_OD.c.i

src/core/CANopen/objDict/CO_OD.s: src/core/CANopen/objDict/CO_OD.c.s

.PHONY : src/core/CANopen/objDict/CO_OD.s

# target to generate assembly for a file
src/core/CANopen/objDict/CO_OD.c.s:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/CANopen/objDict/CO_OD.c.s
.PHONY : src/core/CANopen/objDict/CO_OD.c.s

src/core/application.o: src/core/application.cpp.o

.PHONY : src/core/application.o

# target to build an object file
src/core/application.cpp.o:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/application.cpp.o
.PHONY : src/core/application.cpp.o

src/core/application.i: src/core/application.cpp.i

.PHONY : src/core/application.i

# target to preprocess a source file
src/core/application.cpp.i:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/application.cpp.i
.PHONY : src/core/application.cpp.i

src/core/application.s: src/core/application.cpp.s

.PHONY : src/core/application.s

# target to generate assembly for a file
src/core/application.cpp.s:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/application.cpp.s
.PHONY : src/core/application.cpp.s

src/core/main.o: src/core/main.cpp.o

.PHONY : src/core/main.o

# target to build an object file
src/core/main.cpp.o:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/main.cpp.o
.PHONY : src/core/main.cpp.o

src/core/main.i: src/core/main.cpp.i

.PHONY : src/core/main.i

# target to preprocess a source file
src/core/main.cpp.i:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/main.cpp.i
.PHONY : src/core/main.cpp.i

src/core/main.s: src/core/main.cpp.s

.PHONY : src/core/main.s

# target to generate assembly for a file
src/core/main.cpp.s:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/main.cpp.s
.PHONY : src/core/main.cpp.s

src/core/robot/ActuatedJoint.o: src/core/robot/ActuatedJoint.cpp.o

.PHONY : src/core/robot/ActuatedJoint.o

# target to build an object file
src/core/robot/ActuatedJoint.cpp.o:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/robot/ActuatedJoint.cpp.o
.PHONY : src/core/robot/ActuatedJoint.cpp.o

src/core/robot/ActuatedJoint.i: src/core/robot/ActuatedJoint.cpp.i

.PHONY : src/core/robot/ActuatedJoint.i

# target to preprocess a source file
src/core/robot/ActuatedJoint.cpp.i:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/robot/ActuatedJoint.cpp.i
.PHONY : src/core/robot/ActuatedJoint.cpp.i

src/core/robot/ActuatedJoint.s: src/core/robot/ActuatedJoint.cpp.s

.PHONY : src/core/robot/ActuatedJoint.s

# target to generate assembly for a file
src/core/robot/ActuatedJoint.cpp.s:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/robot/ActuatedJoint.cpp.s
.PHONY : src/core/robot/ActuatedJoint.cpp.s

src/core/robot/Drive.o: src/core/robot/Drive.cpp.o

.PHONY : src/core/robot/Drive.o

# target to build an object file
src/core/robot/Drive.cpp.o:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/robot/Drive.cpp.o
.PHONY : src/core/robot/Drive.cpp.o

src/core/robot/Drive.i: src/core/robot/Drive.cpp.i

.PHONY : src/core/robot/Drive.i

# target to preprocess a source file
src/core/robot/Drive.cpp.i:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/robot/Drive.cpp.i
.PHONY : src/core/robot/Drive.cpp.i

src/core/robot/Drive.s: src/core/robot/Drive.cpp.s

.PHONY : src/core/robot/Drive.s

# target to generate assembly for a file
src/core/robot/Drive.cpp.s:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/robot/Drive.cpp.s
.PHONY : src/core/robot/Drive.cpp.s

src/core/robot/InputDevice.o: src/core/robot/InputDevice.cpp.o

.PHONY : src/core/robot/InputDevice.o

# target to build an object file
src/core/robot/InputDevice.cpp.o:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/robot/InputDevice.cpp.o
.PHONY : src/core/robot/InputDevice.cpp.o

src/core/robot/InputDevice.i: src/core/robot/InputDevice.cpp.i

.PHONY : src/core/robot/InputDevice.i

# target to preprocess a source file
src/core/robot/InputDevice.cpp.i:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/robot/InputDevice.cpp.i
.PHONY : src/core/robot/InputDevice.cpp.i

src/core/robot/InputDevice.s: src/core/robot/InputDevice.cpp.s

.PHONY : src/core/robot/InputDevice.s

# target to generate assembly for a file
src/core/robot/InputDevice.cpp.s:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/robot/InputDevice.cpp.s
.PHONY : src/core/robot/InputDevice.cpp.s

src/core/robot/Joint.o: src/core/robot/Joint.cpp.o

.PHONY : src/core/robot/Joint.o

# target to build an object file
src/core/robot/Joint.cpp.o:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/robot/Joint.cpp.o
.PHONY : src/core/robot/Joint.cpp.o

src/core/robot/Joint.i: src/core/robot/Joint.cpp.i

.PHONY : src/core/robot/Joint.i

# target to preprocess a source file
src/core/robot/Joint.cpp.i:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/robot/Joint.cpp.i
.PHONY : src/core/robot/Joint.cpp.i

src/core/robot/Joint.s: src/core/robot/Joint.cpp.s

.PHONY : src/core/robot/Joint.s

# target to generate assembly for a file
src/core/robot/Joint.cpp.s:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/robot/Joint.cpp.s
.PHONY : src/core/robot/Joint.cpp.s

src/core/robot/Robot.o: src/core/robot/Robot.cpp.o

.PHONY : src/core/robot/Robot.o

# target to build an object file
src/core/robot/Robot.cpp.o:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/robot/Robot.cpp.o
.PHONY : src/core/robot/Robot.cpp.o

src/core/robot/Robot.i: src/core/robot/Robot.cpp.i

.PHONY : src/core/robot/Robot.i

# target to preprocess a source file
src/core/robot/Robot.cpp.i:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/robot/Robot.cpp.i
.PHONY : src/core/robot/Robot.cpp.i

src/core/robot/Robot.s: src/core/robot/Robot.cpp.s

.PHONY : src/core/robot/Robot.s

# target to generate assembly for a file
src/core/robot/Robot.cpp.s:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/robot/Robot.cpp.s
.PHONY : src/core/robot/Robot.cpp.s

src/core/stateMachine/Event.o: src/core/stateMachine/Event.cpp.o

.PHONY : src/core/stateMachine/Event.o

# target to build an object file
src/core/stateMachine/Event.cpp.o:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/stateMachine/Event.cpp.o
.PHONY : src/core/stateMachine/Event.cpp.o

src/core/stateMachine/Event.i: src/core/stateMachine/Event.cpp.i

.PHONY : src/core/stateMachine/Event.i

# target to preprocess a source file
src/core/stateMachine/Event.cpp.i:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/stateMachine/Event.cpp.i
.PHONY : src/core/stateMachine/Event.cpp.i

src/core/stateMachine/Event.s: src/core/stateMachine/Event.cpp.s

.PHONY : src/core/stateMachine/Event.s

# target to generate assembly for a file
src/core/stateMachine/Event.cpp.s:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/stateMachine/Event.cpp.s
.PHONY : src/core/stateMachine/Event.cpp.s

src/core/stateMachine/State.o: src/core/stateMachine/State.cpp.o

.PHONY : src/core/stateMachine/State.o

# target to build an object file
src/core/stateMachine/State.cpp.o:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/stateMachine/State.cpp.o
.PHONY : src/core/stateMachine/State.cpp.o

src/core/stateMachine/State.i: src/core/stateMachine/State.cpp.i

.PHONY : src/core/stateMachine/State.i

# target to preprocess a source file
src/core/stateMachine/State.cpp.i:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/stateMachine/State.cpp.i
.PHONY : src/core/stateMachine/State.cpp.i

src/core/stateMachine/State.s: src/core/stateMachine/State.cpp.s

.PHONY : src/core/stateMachine/State.s

# target to generate assembly for a file
src/core/stateMachine/State.cpp.s:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/stateMachine/State.cpp.s
.PHONY : src/core/stateMachine/State.cpp.s

src/core/stateMachine/StateMachine.o: src/core/stateMachine/StateMachine.cpp.o

.PHONY : src/core/stateMachine/StateMachine.o

# target to build an object file
src/core/stateMachine/StateMachine.cpp.o:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/stateMachine/StateMachine.cpp.o
.PHONY : src/core/stateMachine/StateMachine.cpp.o

src/core/stateMachine/StateMachine.i: src/core/stateMachine/StateMachine.cpp.i

.PHONY : src/core/stateMachine/StateMachine.i

# target to preprocess a source file
src/core/stateMachine/StateMachine.cpp.i:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/stateMachine/StateMachine.cpp.i
.PHONY : src/core/stateMachine/StateMachine.cpp.i

src/core/stateMachine/StateMachine.s: src/core/stateMachine/StateMachine.cpp.s

.PHONY : src/core/stateMachine/StateMachine.s

# target to generate assembly for a file
src/core/stateMachine/StateMachine.cpp.s:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/stateMachine/StateMachine.cpp.s
.PHONY : src/core/stateMachine/StateMachine.cpp.s

src/core/stateMachine/Transition.o: src/core/stateMachine/Transition.cpp.o

.PHONY : src/core/stateMachine/Transition.o

# target to build an object file
src/core/stateMachine/Transition.cpp.o:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/stateMachine/Transition.cpp.o
.PHONY : src/core/stateMachine/Transition.cpp.o

src/core/stateMachine/Transition.i: src/core/stateMachine/Transition.cpp.i

.PHONY : src/core/stateMachine/Transition.i

# target to preprocess a source file
src/core/stateMachine/Transition.cpp.i:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/stateMachine/Transition.cpp.i
.PHONY : src/core/stateMachine/Transition.cpp.i

src/core/stateMachine/Transition.s: src/core/stateMachine/Transition.cpp.s

.PHONY : src/core/stateMachine/Transition.s

# target to generate assembly for a file
src/core/stateMachine/Transition.cpp.s:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/core/stateMachine/Transition.cpp.s
.PHONY : src/core/stateMachine/Transition.cpp.s

src/hardware/IO/Joystick.o: src/hardware/IO/Joystick.cpp.o

.PHONY : src/hardware/IO/Joystick.o

# target to build an object file
src/hardware/IO/Joystick.cpp.o:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/hardware/IO/Joystick.cpp.o
.PHONY : src/hardware/IO/Joystick.cpp.o

src/hardware/IO/Joystick.i: src/hardware/IO/Joystick.cpp.i

.PHONY : src/hardware/IO/Joystick.i

# target to preprocess a source file
src/hardware/IO/Joystick.cpp.i:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/hardware/IO/Joystick.cpp.i
.PHONY : src/hardware/IO/Joystick.cpp.i

src/hardware/IO/Joystick.s: src/hardware/IO/Joystick.cpp.s

.PHONY : src/hardware/IO/Joystick.s

# target to generate assembly for a file
src/hardware/IO/Joystick.cpp.s:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/hardware/IO/Joystick.cpp.s
.PHONY : src/hardware/IO/Joystick.cpp.s

src/hardware/IO/Keyboard.o: src/hardware/IO/Keyboard.cpp.o

.PHONY : src/hardware/IO/Keyboard.o

# target to build an object file
src/hardware/IO/Keyboard.cpp.o:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/hardware/IO/Keyboard.cpp.o
.PHONY : src/hardware/IO/Keyboard.cpp.o

src/hardware/IO/Keyboard.i: src/hardware/IO/Keyboard.cpp.i

.PHONY : src/hardware/IO/Keyboard.i

# target to preprocess a source file
src/hardware/IO/Keyboard.cpp.i:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/hardware/IO/Keyboard.cpp.i
.PHONY : src/hardware/IO/Keyboard.cpp.i

src/hardware/IO/Keyboard.s: src/hardware/IO/Keyboard.cpp.s

.PHONY : src/hardware/IO/Keyboard.s

# target to generate assembly for a file
src/hardware/IO/Keyboard.cpp.s:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/hardware/IO/Keyboard.cpp.s
.PHONY : src/hardware/IO/Keyboard.cpp.s

src/hardware/drives/CopleyDrive.o: src/hardware/drives/CopleyDrive.cpp.o

.PHONY : src/hardware/drives/CopleyDrive.o

# target to build an object file
src/hardware/drives/CopleyDrive.cpp.o:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/hardware/drives/CopleyDrive.cpp.o
.PHONY : src/hardware/drives/CopleyDrive.cpp.o

src/hardware/drives/CopleyDrive.i: src/hardware/drives/CopleyDrive.cpp.i

.PHONY : src/hardware/drives/CopleyDrive.i

# target to preprocess a source file
src/hardware/drives/CopleyDrive.cpp.i:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/hardware/drives/CopleyDrive.cpp.i
.PHONY : src/hardware/drives/CopleyDrive.cpp.i

src/hardware/drives/CopleyDrive.s: src/hardware/drives/CopleyDrive.cpp.s

.PHONY : src/hardware/drives/CopleyDrive.s

# target to generate assembly for a file
src/hardware/drives/CopleyDrive.cpp.s:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/hardware/drives/CopleyDrive.cpp.s
.PHONY : src/hardware/drives/CopleyDrive.cpp.s

src/hardware/drives/KincoDrive.o: src/hardware/drives/KincoDrive.cpp.o

.PHONY : src/hardware/drives/KincoDrive.o

# target to build an object file
src/hardware/drives/KincoDrive.cpp.o:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/hardware/drives/KincoDrive.cpp.o
.PHONY : src/hardware/drives/KincoDrive.cpp.o

src/hardware/drives/KincoDrive.i: src/hardware/drives/KincoDrive.cpp.i

.PHONY : src/hardware/drives/KincoDrive.i

# target to preprocess a source file
src/hardware/drives/KincoDrive.cpp.i:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/hardware/drives/KincoDrive.cpp.i
.PHONY : src/hardware/drives/KincoDrive.cpp.i

src/hardware/drives/KincoDrive.s: src/hardware/drives/KincoDrive.cpp.s

.PHONY : src/hardware/drives/KincoDrive.s

# target to generate assembly for a file
src/hardware/drives/KincoDrive.cpp.s:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/hardware/drives/KincoDrive.cpp.s
.PHONY : src/hardware/drives/KincoDrive.cpp.s

src/hardware/platforms/M1/JointM1.o: src/hardware/platforms/M1/JointM1.cpp.o

.PHONY : src/hardware/platforms/M1/JointM1.o

# target to build an object file
src/hardware/platforms/M1/JointM1.cpp.o:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/hardware/platforms/M1/JointM1.cpp.o
.PHONY : src/hardware/platforms/M1/JointM1.cpp.o

src/hardware/platforms/M1/JointM1.i: src/hardware/platforms/M1/JointM1.cpp.i

.PHONY : src/hardware/platforms/M1/JointM1.i

# target to preprocess a source file
src/hardware/platforms/M1/JointM1.cpp.i:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/hardware/platforms/M1/JointM1.cpp.i
.PHONY : src/hardware/platforms/M1/JointM1.cpp.i

src/hardware/platforms/M1/JointM1.s: src/hardware/platforms/M1/JointM1.cpp.s

.PHONY : src/hardware/platforms/M1/JointM1.s

# target to generate assembly for a file
src/hardware/platforms/M1/JointM1.cpp.s:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/hardware/platforms/M1/JointM1.cpp.s
.PHONY : src/hardware/platforms/M1/JointM1.cpp.s

src/hardware/platforms/M1/RobotM1.o: src/hardware/platforms/M1/RobotM1.cpp.o

.PHONY : src/hardware/platforms/M1/RobotM1.o

# target to build an object file
src/hardware/platforms/M1/RobotM1.cpp.o:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/hardware/platforms/M1/RobotM1.cpp.o
.PHONY : src/hardware/platforms/M1/RobotM1.cpp.o

src/hardware/platforms/M1/RobotM1.i: src/hardware/platforms/M1/RobotM1.cpp.i

.PHONY : src/hardware/platforms/M1/RobotM1.i

# target to preprocess a source file
src/hardware/platforms/M1/RobotM1.cpp.i:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/hardware/platforms/M1/RobotM1.cpp.i
.PHONY : src/hardware/platforms/M1/RobotM1.cpp.i

src/hardware/platforms/M1/RobotM1.s: src/hardware/platforms/M1/RobotM1.cpp.s

.PHONY : src/hardware/platforms/M1/RobotM1.s

# target to generate assembly for a file
src/hardware/platforms/M1/RobotM1.cpp.s:
	$(MAKE) -f CMakeFiles/M1DemoMachine_APP.dir/build.make CMakeFiles/M1DemoMachine_APP.dir/src/hardware/platforms/M1/RobotM1.cpp.s
.PHONY : src/hardware/platforms/M1/RobotM1.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... M1DemoMachine_APP"
	@echo "... edit_cache"
	@echo "... src/apps/M1DemoMachine/M1DemoMachine.o"
	@echo "... src/apps/M1DemoMachine/M1DemoMachine.i"
	@echo "... src/apps/M1DemoMachine/M1DemoMachine.s"
	@echo "... src/apps/M1DemoMachine/M1DemoStates.o"
	@echo "... src/apps/M1DemoMachine/M1DemoStates.i"
	@echo "... src/apps/M1DemoMachine/M1DemoStates.s"
	@echo "... src/core/CANopen/CANcomms/CO_comm_helpers.o"
	@echo "... src/core/CANopen/CANcomms/CO_comm_helpers.i"
	@echo "... src/core/CANopen/CANcomms/CO_comm_helpers.s"
	@echo "... src/core/CANopen/CANcomms/CO_command.o"
	@echo "... src/core/CANopen/CANcomms/CO_command.i"
	@echo "... src/core/CANopen/CANcomms/CO_command.s"
	@echo "... src/core/CANopen/CANcomms/CO_master.o"
	@echo "... src/core/CANopen/CANcomms/CO_master.i"
	@echo "... src/core/CANopen/CANcomms/CO_master.s"
	@echo "... src/core/CANopen/CANcomms/CO_time.o"
	@echo "... src/core/CANopen/CANcomms/CO_time.i"
	@echo "... src/core/CANopen/CANcomms/CO_time.s"
	@echo "... src/core/CANopen/CANopenNode/CANopen.o"
	@echo "... src/core/CANopen/CANopenNode/CANopen.i"
	@echo "... src/core/CANopen/CANopenNode/CANopen.s"
	@echo "... src/core/CANopen/CANopenNode/stack/CO_Emergency.o"
	@echo "... src/core/CANopen/CANopenNode/stack/CO_Emergency.i"
	@echo "... src/core/CANopen/CANopenNode/stack/CO_Emergency.s"
	@echo "... src/core/CANopen/CANopenNode/stack/CO_HBconsumer.o"
	@echo "... src/core/CANopen/CANopenNode/stack/CO_HBconsumer.i"
	@echo "... src/core/CANopen/CANopenNode/stack/CO_HBconsumer.s"
	@echo "... src/core/CANopen/CANopenNode/stack/CO_NMT_Heartbeat.o"
	@echo "... src/core/CANopen/CANopenNode/stack/CO_NMT_Heartbeat.i"
	@echo "... src/core/CANopen/CANopenNode/stack/CO_NMT_Heartbeat.s"
	@echo "... src/core/CANopen/CANopenNode/stack/CO_PDO.o"
	@echo "... src/core/CANopen/CANopenNode/stack/CO_PDO.i"
	@echo "... src/core/CANopen/CANopenNode/stack/CO_PDO.s"
	@echo "... src/core/CANopen/CANopenNode/stack/CO_SDO.o"
	@echo "... src/core/CANopen/CANopenNode/stack/CO_SDO.i"
	@echo "... src/core/CANopen/CANopenNode/stack/CO_SDO.s"
	@echo "... src/core/CANopen/CANopenNode/stack/CO_SDOmaster.o"
	@echo "... src/core/CANopen/CANopenNode/stack/CO_SDOmaster.i"
	@echo "... src/core/CANopen/CANopenNode/stack/CO_SDOmaster.s"
	@echo "... src/core/CANopen/CANopenNode/stack/CO_SYNC.o"
	@echo "... src/core/CANopen/CANopenNode/stack/CO_SYNC.i"
	@echo "... src/core/CANopen/CANopenNode/stack/CO_SYNC.s"
	@echo "... src/core/CANopen/CANopenNode/stack/CO_trace.o"
	@echo "... src/core/CANopen/CANopenNode/stack/CO_trace.i"
	@echo "... src/core/CANopen/CANopenNode/stack/CO_trace.s"
	@echo "... src/core/CANopen/CANopenNode/stack/crc16-ccitt.o"
	@echo "... src/core/CANopen/CANopenNode/stack/crc16-ccitt.i"
	@echo "... src/core/CANopen/CANopenNode/stack/crc16-ccitt.s"
	@echo "... src/core/CANopen/CANopenNode/stack/socketCAN/CO_Linux_tasks.o"
	@echo "... src/core/CANopen/CANopenNode/stack/socketCAN/CO_Linux_tasks.i"
	@echo "... src/core/CANopen/CANopenNode/stack/socketCAN/CO_Linux_tasks.s"
	@echo "... src/core/CANopen/CANopenNode/stack/socketCAN/CO_OD_storage.o"
	@echo "... src/core/CANopen/CANopenNode/stack/socketCAN/CO_OD_storage.i"
	@echo "... src/core/CANopen/CANopenNode/stack/socketCAN/CO_OD_storage.s"
	@echo "... src/core/CANopen/CANopenNode/stack/socketCAN/CO_driver.o"
	@echo "... src/core/CANopen/CANopenNode/stack/socketCAN/CO_driver.i"
	@echo "... src/core/CANopen/CANopenNode/stack/socketCAN/CO_driver.s"
	@echo "... src/core/CANopen/objDict/CO_OD.o"
	@echo "... src/core/CANopen/objDict/CO_OD.i"
	@echo "... src/core/CANopen/objDict/CO_OD.s"
	@echo "... src/core/application.o"
	@echo "... src/core/application.i"
	@echo "... src/core/application.s"
	@echo "... src/core/main.o"
	@echo "... src/core/main.i"
	@echo "... src/core/main.s"
	@echo "... src/core/robot/ActuatedJoint.o"
	@echo "... src/core/robot/ActuatedJoint.i"
	@echo "... src/core/robot/ActuatedJoint.s"
	@echo "... src/core/robot/Drive.o"
	@echo "... src/core/robot/Drive.i"
	@echo "... src/core/robot/Drive.s"
	@echo "... src/core/robot/InputDevice.o"
	@echo "... src/core/robot/InputDevice.i"
	@echo "... src/core/robot/InputDevice.s"
	@echo "... src/core/robot/Joint.o"
	@echo "... src/core/robot/Joint.i"
	@echo "... src/core/robot/Joint.s"
	@echo "... src/core/robot/Robot.o"
	@echo "... src/core/robot/Robot.i"
	@echo "... src/core/robot/Robot.s"
	@echo "... src/core/stateMachine/Event.o"
	@echo "... src/core/stateMachine/Event.i"
	@echo "... src/core/stateMachine/Event.s"
	@echo "... src/core/stateMachine/State.o"
	@echo "... src/core/stateMachine/State.i"
	@echo "... src/core/stateMachine/State.s"
	@echo "... src/core/stateMachine/StateMachine.o"
	@echo "... src/core/stateMachine/StateMachine.i"
	@echo "... src/core/stateMachine/StateMachine.s"
	@echo "... src/core/stateMachine/Transition.o"
	@echo "... src/core/stateMachine/Transition.i"
	@echo "... src/core/stateMachine/Transition.s"
	@echo "... src/hardware/IO/Joystick.o"
	@echo "... src/hardware/IO/Joystick.i"
	@echo "... src/hardware/IO/Joystick.s"
	@echo "... src/hardware/IO/Keyboard.o"
	@echo "... src/hardware/IO/Keyboard.i"
	@echo "... src/hardware/IO/Keyboard.s"
	@echo "... src/hardware/drives/CopleyDrive.o"
	@echo "... src/hardware/drives/CopleyDrive.i"
	@echo "... src/hardware/drives/CopleyDrive.s"
	@echo "... src/hardware/drives/KincoDrive.o"
	@echo "... src/hardware/drives/KincoDrive.i"
	@echo "... src/hardware/drives/KincoDrive.s"
	@echo "... src/hardware/platforms/M1/JointM1.o"
	@echo "... src/hardware/platforms/M1/JointM1.i"
	@echo "... src/hardware/platforms/M1/JointM1.s"
	@echo "... src/hardware/platforms/M1/RobotM1.o"
	@echo "... src/hardware/platforms/M1/RobotM1.i"
	@echo "... src/hardware/platforms/M1/RobotM1.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

